// Package oracle holds regression tests that compare lvrsrc's parse output
// against pylabview-derived oracle baselines committed under testdata/oracle.
//
// The baselines are generated by scripts/gen-oracle.py and checked in as
// JSON so CI does not need a Python environment. Refresh them with:
//
//	python3 scripts/gen-oracle.py
//
// when the corpus or pylabview changes.
package oracle
